@echo off
start C:\PyCryptoBot\1INCH-USD.lnk
timeout 15
start C:\PyCryptoBot\AAVE-USD.lnk
timeout 15
start C:\PyCryptoBot\ACH-USD.lnk
timeout 15
start C:\PyCryptoBot\ADA-USD.lnk
timeout 15
start C:\PyCryptoBot\ALGO-USD.lnk
timeout 15
start C:\PyCryptoBot\AMP-USD.lnk
timeout 15
start C:\PyCryptoBot\ANKR-USD.lnk
timeout 15
start C:\PyCryptoBot\ATOM-USD.lnk
timeout 15
start C:\PyCryptoBot\AXS-USD.lnk
timeout 15
start C:\PyCryptoBot\BAL-USD.lnk
timeout 15
start C:\PyCryptoBot\BAND-USD.lnk
timeout 15
start C:\PyCryptoBot\BAT-USD.lnk
timeout 15
start C:\PyCryptoBot\BCH-USD.lnk
timeout 15
start C:\PyCryptoBot\BNT-USD.lnk
timeout 15
start C:\PyCryptoBot\BOND-USD.lnk
timeout 15
start C:\PyCryptoBot\BTC-USD.lnk
timeout 15
start C:\PyCryptoBot\CGLD-USD.lnk
timeout 15
start C:\PyCryptoBot\CHZ-USD.lnk
timeout 15
start C:\PyCryptoBot\CLV-USD.lnk
timeout 15
start C:\PyCryptoBot\COMP-USD.lnk
timeout 15
start C:\PyCryptoBot\COTI-USD.lnk
timeout 15
start C:\PyCryptoBot\CRV-USD.lnk
timeout 15
start C:\PyCryptoBot\CTSI-USD.lnk
timeout 15
start C:\PyCryptoBot\DASH-USD.lnk
timeout 15
start C:\PyCryptoBot\DDX-USD.lnk
timeout 15
start C:\PyCryptoBot\DOGE-USD.lnk
timeout 15
start C:\PyCryptoBot\DOT-USD.lnk
timeout 15
start C:\PyCryptoBot\ENJ-USD.lnk
timeout 15
start C:\PyCryptoBot\EOS-USD.lnk
timeout 15
start C:\PyCryptoBot\ETC-USD.lnk
timeout 15
start C:\PyCryptoBot\ETH-USD.lnk
timeout 15
start C:\PyCryptoBot\FARM-USD.lnk
timeout 15
start C:\PyCryptoBot\FET-USD.lnk
timeout 15
start C:\PyCryptoBot\FIL-USD.lnk
timeout 15
start C:\PyCryptoBot\FORTH-USD.lnk
timeout 15
start C:\PyCryptoBot\GRT-USD.lnk
timeout 15
start C:\PyCryptoBot\GTC-USD.lnk
timeout 15
start C:\PyCryptoBot\ICP-USD.lnk
timeout 15
start C:\PyCryptoBot\IOTX-USD.lnk
timeout 15
start C:\PyCryptoBot\KEEP-USD.lnk
timeout 15
start C:\PyCryptoBot\KNC-USD.lnk
timeout 15
start C:\PyCryptoBot\LINK-USD.lnk
timeout 15
start C:\PyCryptoBot\LPT-USD.lnk
timeout 15
start C:\PyCryptoBot\LRC-USD.lnk
timeout 15
start C:\PyCryptoBot\LTC-USD.lnk
timeout 15
start C:\PyCryptoBot\MANA-USD.lnk
timeout 15
start C:\PyCryptoBot\MASK-USD.lnk
timeout 15
start C:\PyCryptoBot\MATIC-USD.lnk
timeout 15
start C:\PyCryptoBot\MIR-USD.lnk
timeout 15
start C:\PyCryptoBot\MKR-USD.lnk
timeout 15
start C:\PyCryptoBot\MLN-USD.lnk
timeout 15
start C:\PyCryptoBot\NKN-USD.lnk
timeout 15
start C:\PyCryptoBot\NMR-USD.lnk
timeout 15
start C:\PyCryptoBot\NU-USD.lnk
timeout 15
start C:\PyCryptoBot\OGN-USD.lnk
timeout 15
start C:\PyCryptoBot\OMG-USD.lnk
timeout 15
start C:\PyCryptoBot\ORN-USD.lnk
timeout 15
start C:\PyCryptoBot\OXT-USD.lnk
timeout 15
start C:\PyCryptoBot\PLA-USD.lnk
timeout 15
start C:\PyCryptoBot\POLY-USD.lnk
timeout 15
start C:\PyCryptoBot\QNT-USD.lnk
timeout 15
start C:\PyCryptoBot\QUICK-USD.lnk
timeout 15
start C:\PyCryptoBot\RAD-USD.lnk
timeout 15
start C:\PyCryptoBot\RAI-USD.lnk
timeout 15
start C:\PyCryptoBot\REN-USD.lnk
timeout 15
start C:\PyCryptoBot\REP-USD.lnk
timeout 15
start C:\PyCryptoBot\REQ-USD.lnk
timeout 15
start C:\PyCryptoBot\RLC-USD.lnk
timeout 15
start C:\PyCryptoBot\RLY-USD.lnk
timeout 15
start C:\PyCryptoBot\SKL-USD.lnk
timeout 15
start C:\PyCryptoBot\SNX-USD.lnk
timeout 15
start C:\PyCryptoBot\SOL-USD.lnk
timeout 15
start C:\PyCryptoBot\STORJ-USD.lnk
timeout 15
start C:\PyCryptoBot\SUSHI-USD.lnk
timeout 15
start C:\PyCryptoBot\TRB-USD.lnk
timeout 15
start C:\PyCryptoBot\TRIBE-USD.lnk
timeout 15
start C:\PyCryptoBot\TRU-USD.lnk
timeout 15
start C:\PyCryptoBot\UMA-USD.lnk
timeout 15
start C:\PyCryptoBot\UNI-USD.lnk
timeout 15
start C:\PyCryptoBot\WBTC-USD.lnk
timeout 15
start C:\PyCryptoBot\WLUNA-USD.lnk
timeout 15
start C:\PyCryptoBot\XLM-USD.lnk
timeout 15
start C:\PyCryptoBot\XTZ-USD.lnk
timeout 15
start C:\PyCryptoBot\YFII-USD.lnk
timeout 15
start C:\PyCryptoBot\YFI-USD.lnk
timeout 15
start C:\PyCryptoBot\ZEC-USD.lnk
timeout 15
start C:\PyCryptoBot\ZRX-USD.lnk
timeout 15
exit